import { Raleway } from 'next/font/google'
import '../styles/globals.css'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import Provider from '@/components/Provider' 

const raleway = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'MbaKaro-Distance Learning Guide',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-4G2D7Q2H0W"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
      
        gtag('config', 'G-4G2D7Q2H0W');
      </script>
      <body className={raleway.className}>
        <Provider>
          <Nav/>
          {children}
          <Footer/>
        </Provider>
      </body>
    </html>
  )
}
